### ISSUE TITLE
Subscribed to yearly sub after trial expired. Bot won't post anymore. 

### ISSUE THREAD

**Issue by Hemalurgist** [dblock/discord-strava#23]
Three days after our discord server's free trial expired I signed up for the yearly sub. Bot won't post anyone's activities anymore.  Still responds to commands like linking Strava accounts and can configure activity fields. Kicked and re-added bot hoping this will help. Will report back once someone does an activity.

**Comment by dblock** [comment]
There shouldn't be a delay in activities, so it's telling me something is wrong. Drop me a note to dblock at vestris dot com with your team name and I can take a look?
