### ISSUE TITLE
Activity start time incorrect

### ISSUE THREAD

**Issue by theinversepixel** [dblock/discord-strava#27]
I have a small issue that began yesterday, all activities are displaying in Discord as 4 hours in the future of when they were done.

**Comment by dblock** [comment]
The bot itself runs in ET (UTC-4), so the 4 hours looks suspicious, this could be a bug introduced with the Ruby upgrade in https://github.com/dblock/discord-strava/commit/606e251d602a4f992260e2e96afc202f873a8cdf. 

The time displayed is local start time that comes as is from Strava (https://github.com/dblock/discord-strava/blob/606e251d602a4f992260e2e96afc202f873a8cdf/discord-strava/models/user_activity.rb#L20). Does Strava show a different time in their website/app than what the bot shows?

Do you have a screenshot and a link to Strava for the activity that's displayed incorrectly? Feel free to email me at dblock at dblock dot org if you don't want to post it here.
