### ISSUE TITLE
Unbragged activities don't catch up

### ISSUE THREAD

**Issue by adepssimius** [dblock/discord-strava#8]
Hey, me again!

I have the bot registered to two servers. One is still on a trial and posts the correct activity upon activity completion.

![Screenshot_20240110-173758.png](https://github.com/dblock/discord-strava/assets/5257052/5e656c48-abb6-4c35-9e67-53bf5c5c5a65)

The other server ran out of trial, was subsequently subscribed with a paid subscription and simultaneously posts an incorrect, old activity and does not post recently completed activities.

![Screenshot_20240110-173818.png](https://github.com/dblock/discord-strava/assets/5257052/bfd64c3f-5a50-49f1-9bda-31d47fec9185)

**Comment by dblock** [comment]
The one that ran out of subscription and was subscribed is probably just catching up. Give it 24 hours and comment if it hasn't?

**Comment by adepssimius** [comment]
It doesn't appear to be catching up, it appears to be posting the next workout chronologically. This is the Dadia guild.

 The other guild where I have the bot running posts the activity that was completed when an activity is completed. In the Dadia guild, when I complete an activity it appears to post the next activity that has not yet been posted and no more. For instance when I posted two activities this morning both activities from today showed up as expected in the other guild, but the two activities I did on Jan 3rd showed up in the Dadia guild.

**Comment by dblock** [comment]
I think I fixed it with https://github.com/dblock/discord-strava/commit/52f604ff571a814fb01611d14d4af4e2048c9964. 

This guild had 14 activities that were yet to be posted. I also manually flushed these old activities. Reopen if the problem persists.

**Comment by adepssimius** [comment]
Thank you! Will do.

**Comment by adepssimius** [comment]
Everything is performing as expected currently. Thanks for your help here.
